### ISSUE TITLE
Incohérence dans le format du fichier XML

### ISSUE THREAD

**Issue by johancros** [DGFiP/Test-Compta-Demat#11]
Bonsoir, 

Nous avons un problème avec le contenu du fichier XML à fournir. 
Nous avons sur certaines écritures plusieurs date de lettrage pour une même écriture.
Comment faire dans ce cas ? Car la date de lettrage est à fournir dans l'élément <ecriture> et non dans l'élément du fichier XML <ligne>

J'ai trouvé très peu d'éléments sur le format XML, j'ai l'impression que ce format est très peu utilisé.

Nous vous remercions par avance.

**Comment by TheDwarf71** [comment]
Bonjour,

Je ne suis pas spécialiste des contrôles fiscales, mais : 
- Que ce soit en XML ou CSV, un seul champs Date de lettrage est possible pour une écriture
- Il faut choisir quelle est la date qui vous semble la plus pertinente, et surtout expliquer ce choix dans la documentation qui doit accompagner le fichier lors d'un contrôle fiscale.

Je laisse le soin aux plus qualifiés de me reprendre.

Bonne journée

**Comment by tola2** [comment]
Bonjour,
La structure du fichier XSD n’autorise que l’affichage d’une unique date de lettrage par écriture (l’affichage d’une date de lettrage par ligne est impossible). Le choix ayant été fait de ne pas modifier le fichier XSD, il est recommandé au contribuable de ne pas saisir de date de lettrage et de ne conserver que le lettrage des écritures, qui permet à l’entreprise d’assurer un suivi des règlements de ses clients et fournisseurs. En effet, l’absence de date de lettrage ne peut  être opposée  au contribuable  puisque la saisie du champ « DateLet » n’est pas rendue obligatoire, conformément aux dispositions de l’article A 47 A-1 du LPF.  

Cordialement.
