### ISSUE TITLE
Débit/crédit à zéro

### ISSUE THREAD

**Issue by bnelissen-orisha** [DGFiP/Test-Compta-Demat#23]
Bonjour,

L'anomalie suivant apparaît régulièrement :
`Structure du fichier oncorrect, débit/crédit... renseignés sur une même ligne..., ou débit=crédit=0 [xxxx] fois dans le fichier`

Hors le logiciel comptable que nous utilisons autorise les écritures à zéro. Et je ne trouve pas d'interdiction de la présence de débit/crédit à zéro dans l'article A.47 A-1 du Livre des Procédures Fiscales.

Pourriez-vous m'éclairer sur le sujet ?
Merci.

Benoît NELISSEN

**Comment by bnelissen-orisha** [comment]
Up ?

**Comment by jpaquit** [comment]
Pouvez-vous reproduire ici la ligne qui pose problème ?

**Comment by bnelissen-orisha** [comment]
Voici une ligne d'écriture avec débit = crédit = 0 :
`ANV	JOURNAL A-NOUVEAUX	99999999999999XXX	20210401	411000	COLLECTIF CLIENTS	    999	XXX	00022960	20120404	FACTURE	,000		000	00000000	20120416	,000	EUR	 	00000000	21210722470000BAT	10054	A	20120603	N`

**Comment by jpaquit** [comment]
J'aurais tendance à dire que la ligne est mal formatée.
Les tabulations rendent la ligne illisible, pouvez-vous utilisez le symbole  "|" comme séparateur de champ ou fournir un fichier plat ?
De plus, pouvez-vous préciser le "Type de revenus" à qualifier ?

**Comment by bnelissen-orisha** [comment]
Voici la ligne avec des pipes (|) au lieu de tabulations :
`ANV|JOURNAL A-NOUVEAUX|99999999999999XXX|20210401|411000|COLLECTIF CLIENTS|    999|XXX|00022960|20120404|FACTURE|,000||000|00000000|20120416|,000|EUR| |00000000|21210722470000BAT|10054|A|20120603|N`

Nous n'avons aucun soucis de formatage, le programme ne nous a jamais sorti ce genre de problème. C'est vraiment le fait que le débit et le crédit soient tous les deux à zéro qui déclenche cet avertissement. Nous nous posons la question du bien fondé de celui-ci étant donné qu'il n'en est pas fait mention dans l'article A.47 A-1 du Livre des Procédures Fiscales.

Qu'appelez vous "Types de revenus" ?

**Comment by jpaquit** [comment]
En fonction du "Types de revenus" (BIC/IS, BNCT, BAT, COM) , le nombre de colonne attendu varie.
Le contrôle sur l'égalité crédit=débit=0 existe depuis 2014 (version 1.00.04) et est géré par ce morceau de code :

```
        unless (
            ( $valeurs[$rang_d] == 0 && $valeurs[$rang_c] != 0 ) ||
            (   $valeurs[$rang_d] != 0 && $valeurs[$rang_c] == 0 )
        ) {
            #RG:F:vérification que tous les lignes d'écritures n'ont pas un débit et un crédit servis:A
            # 11/02/2014 : Mise en alerte, evolution fonctionnelle
            &erreur( "A",
                    "Structure fichier incorrecte, débit/crédit :"
                  . $valeurs[$rang_d] . " / "
                  . $valeurs[$rang_c]
                  . ": renseignés sur une même ligne :$nb_l:  , ou débit=crédit=0 "
            );    #&& &finko ;
        }
```

La simple suppression de ce code permet d'accepter les lignes crédit=débit=0.
Reste à savoir ce qu'en pense la DGFiP.

**Comment by compta-demat** [comment]
Je vous donne la réponse fournie par la dgfip à ce problème 

"
_Les copies des FEC doivent répondre aux normes définies à l’article A. 47 A 1 du livre des procédures fiscales (LPF). Ces normes précisent  la structure informatique autorisée pour le fichier ainsi que les données comptables devant obligatoirement y figurer.


Pour information, la troisième page du rapport généré par  "Test Compta Demat" regroupe différents éléments d'alerte donnés à titre d’information concernant des signalements d’erreurs potentielles liées à des règles comptables de base.  C'est le cas en l'espèce du message  « Structure fichier incorrecte, débit/crédit 0.00 renseignés sur une même ligne, ou débit=crédit=0 ». Ce message a pour but d'informer d'une erreur comptable potentielle, qui peut par ailleurs être expliquée par les conditions d'exercice de l'entreprise.


Le document de synthèse édité par l’outil de test des FEC "Test compta Demat" ne constitue pas une attestation de conformité et ne saurait engager l’administration._

"

Bref : Une ligne crédit/debit à 0 n'est pas une erreur, mais un avertissement est envoyé pour indiquer une erreur comptable potentielle.
