### ISSUE TITLE
Erreur contrôle séparateur des montants pour les fichiers XML

### ISSUE THREAD

**Issue by bizoo** [DGFiP/Test-Compta-Demat#24]
Sur la dernière version (10) le contrôle rapporte des erreurs:
`Le champ CREDIT n'est pas au bon format, ... un format numérique avec un séparateur , au lieu de . est attendu ... ;`

L'ancienne version (06) ne faisait pas les mêmes erreurs.

Selon le XSD disponible sur impots.gouv.fr, les champs montants sont définis en xs:float:
`<xs:element name="Credit" minOccurs="1" maxOccurs="1" type="xs:float"/>`

La norme XSD spécifie que dans ce cas le séparateur est le point.

Si on met une virgule dans les montants, le fichier est également contrôlé non conforme car il ne respecte pas le XSD.

La version 10 est donc inutilisable dans l'état actuel pour tester les fichiers XML.

**Comment by machamar** [comment]
Hi,
How have you resolved your issue?
I'm doing this now and I'm having the same problem.
Thanks and regards,
Márcia

**Comment by bizoo** [comment]
New release from March 5 resolve this issue.

**Comment by machamar** [comment]
Hi,
I was not able to do with this release but only with version 6. Will we
have a problem in case of audit?
Thanks and regards,
Marcia

A quarta, 24/03/2021, 17:58, Dominique Wahli ***@***.***>
escreveu:
