### ISSUE TITLE
Publication of a change file

### ISSUE THREAD

**Issue by pommedeterresautee** [DGFiP/Test-Compta-Demat#3]
A new version has been published and it is required to read the source code in the commit to guess the changes. It would be better if the changes were summarized in a file. Therefore users may test the new behaviors easily.

Kind regards,
Michaël

**Comment by npotelle** [comment]
It was planned to give some informations but your are too impatient ;-)
Changes are now added to the release description.
No file is planned.

**Comment by pommedeterresautee** [comment]
Haha I do to you what users of my open source projects do to me all the time :-) 

Tks for the release information!
